name: poo-python

on: [pull_request, push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install-requirements
      run:
        make install-requirements

    - name: tests
      run:
        make test